name: Notify Merge Conflict
description: Github Action to notify merge conflict pulls
branding:
  icon: alert-octagon
  color: gray-dark
inputs:
  owner:
    description: A string identifier of the owner to retrieve merge conflict pulls.
    required: true
  repo:
    description: A string identifier of the repository to retrieve merge conflict pulls.
    required: true
  token:
    description: A string token to authenticate to Github.
    required: true
  body:
    description: A string body to create issue comments.
    required: false
    default: Merge Conflict found
  dryrun:
    description: A boolean to indicate whether the action creates actual issue comments.
    required: false
    default: "false"
  unknown-state-max-retries:
    description: A number of maximum retries to get a pull state. The `pulls.get` request retries when the response state is `unknown`.
    required: false
    default: "5"
runs:
  using: node12
  main: dist/index.js
