sequenceDiagram
    autonumber

    actor dev as Developer
    participant github as Github
    participant action as merge-conflict-action

    dev ->> github : Merge pull
    github ->> action : on.push.branches.main (body, dryrun)
    action ->> github : pulls.list (state = open, sort = created, direction = desc, per_page = 30)
    github ->> action : pulls (number)

    loop for each pulls
        action ->> github : pulls.get
        github ->> action : pull (mergeable_state, pushed_at)
        alt mergeable_state != "dirty"
            action ->> action : drop
        end
    end

    loop for each pulls
        action ->> github : issues.listComments
        github ->> action : comments (body', created_at)
        alt exists body == body' and created_at > pushed_at
            action ->> action : drop
        end
    end

    loop for each pulls
        alt dryrun == false
            action ->> github : isssues.createComment (body)
            github ->> dev : Notify merge conflict pulls <br> via issue comments subscription <br> (e.g. Slack /github subscribe)
        end
    end
